### ISSUE TITLE
Editing member profile issues

### ISSUE THREAD

**Issue by sergeyf-QA** [tipcat-net/tipcat-net-spa#202]
@sernik73 
1) I need to tap the Edit button on Member profile page twice for opening the Edit menu when I arrived to the page

2) if I enter data to the any edit field and tap 'Cancel' and open a field again then entered data is still at the field

https://user-images.githubusercontent.com/74529212/152813399-0d58807b-e933-4e65-af54-51b985756a9c.MP4

3) I can not close the Edit menu when tap on Edit button

https://user-images.githubusercontent.com/74529212/152813515-5d711d30-58c6-4665-9aca-56d5de86dbd6.MP4

4) when I tap 'Cancel' button after editing field then screen is scrolled to the top of the Edit menu

https://user-images.githubusercontent.com/74529212/152814684-3362d40a-70f2-43e7-87ca-ce9590bd532f.MP4

**Comment by kirillta** [comment]
@sergeyf-QA are you able to edit a member's name? I'm not. The Save button does nothing

**Comment by sergeyf-QA** [comment]
@kirillta 
it works on my side but changes are not applied at once you tap 'Save' due to the caching

**Comment by sergeyf-QA** [comment]
@sernik73 
4th point is not fixed

**Comment by sergeyf-QA** [comment]
the same 4th issue is on /members at the side bar menu

**Comment by sergeyf-QA** [comment]
**Summary:**
- fixes are applied

**OK on DEV.**
