### ISSUE TITLE
Edit Account button doesn't draw the menu on a first click

### ISSUE THREAD

**Issue by kirillta** [tipcat-net/tipcat-net-spa#203]
![Animation](https://user-images.githubusercontent.com/19779590/152861166-1382bfee-3d55-4808-a683-15b9a6fb58a3.gif)

**Comment by sergeyf-QA** [comment]
@sernik73 
the same issue as described in https://github.com/tipcat-net/tipcat-net-spa/issues/202 on Member profile page

**Comment by kirillta** [comment]
Duplicates #202
