### ISSUE TITLE
Member profile

### ISSUE THREAD

**Issue by sernik73** [tipcat-net/tipcat-net-spa#48]
![image](https://user-images.githubusercontent.com/67476518/141069793-86bf1440-6b19-4e0f-8765-c9e2246ba04a.png)
added profile and links to it

**Comment by sernik73** [comment]
![image](https://user-images.githubusercontent.com/67476518/141069793-86bf1440-6b19-4e0f-8765-c9e2246ba04a.png)

**Comment by sergeyf-QA** [comment]
@sernik73 
1) on Member profile page is no 'active/deactivated/invited' indicator
2) on Member profile page all Cancel and Save buttons at Edit fields don't work
3) on Member profile page avatar can not be added
4) on Member profile page left, right and bottom paddings of white area should be less than it is now
5) on Member profile page info from DB (Facility, Position, E-mail etc) should have font-size 14, line-height 15
6) on Member profile page titles (Facility, Position, E-mail etc) should have SF Pro Display font

**Comment by sernik73** [comment]
4. done
5. done
6. layout error

**Comment by sernik73** [comment]
1. done
2. done
3. done

**Comment by sergeyf-QA** [comment]
**Summary:**
- issues on member profile page are fixed.

**OK on DEV.**
