### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by sernik73** [tipcat-net/tipcat-net-spa#50]
fixed logout
[/logout](https://dev.tipcat.net/logout)

**Comment by sergeyf-QA** [comment]
@sernik73 
Log Out button does not logout on /logout page

**Comment by sergeyf-QA** [comment]
**Summary:**
- Sign Out button in the Menu leads to the /logout page
- Sign Out button in the Menu actually logs out an user

**OK on DEV.**
