### ISSUE TITLE
Fixing a bug in the avatar component

### ISSUE THREAD

**Issue by sernik73** [tipcat-net/tipcat-net-spa#56]
![image](https://user-images.githubusercontent.com/67476518/141327593-c9f065e1-bbbc-4d87-bcc9-94aa51aab957.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- avatar is shown well with FirstName only, LastName only, with filled FirstName and LastName and with FirstName and LastName == NULL

**OK on DEV.**
