### ISSUE TITLE
Invite new member

### ISSUE THREAD

**Issue by sernik73** [tipcat-net/tipcat-net-spa#65]

**Comment by sergeyf-QA** [comment]
@sernik73 
1) 'Invite member' text should be 'Invite new member'
2) Back grey button does not work

**Comment by sernik73** [comment]
1. code review https://github.com/tipcat-net/tipcat-net-spa/pull/72

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Invite member'screen is added
- it is possible to invite a new member there
- invited member receives an invitation letter

**OK on DEV.**
